-- 0006 · Clientes de cada negocio (a quienes se les fía).
-- Un mismo nombre no se repite dentro de un negocio (unique nombre+negocio).
create table if not exists public.clientes (
  id         bigint generated by default as identity primary key,
  nombre     text not null,
  telefono   text,
  negocio_id uuid references public.negocios(id),
  creado_en  timestamptz default now(),
  unique (nombre, negocio_id)
);
