-- 0007 · Movimientos: fiados (deuda) y abonos (pago) de cada cliente.
-- Depende de: clientes, negocios, perfiles. Borrado lógico (eliminado_en/por).
create table if not exists public.movimientos (
  id             bigint generated by default as identity primary key,
  cliente_id     bigint not null references public.clientes(id),
  tipo           text not null check (tipo in ('fiado','abono')),
  monto          numeric not null check (monto >= 0),
  concepto       text,
  negocio_id     uuid references public.negocios(id),
  registrado_por uuid default auth.uid() references public.perfiles(id),
  eliminado_en   timestamptz,
  eliminado_por  uuid references public.perfiles(id),
  fecha          timestamptz default now()
);
