-- 0014 · Retroalimentación de usuarios (feedback) por negocio.
-- Cada usuario deja una calificación (1-5) y un comentario; se ve dentro de
-- su propio negocio (mismo aislamiento multi-tenant que el resto de tablas).
-- Depende de: negocios, mi_negocio_id() (0004). No toca otras tablas.
-- Idempotente: create table if not exists / drop policy if exists.

create table if not exists public.feedback (
  id           bigint generated by default as identity primary key,
  negocio_id   uuid not null default public.mi_negocio_id() references public.negocios(id),
  user_id      uuid not null default auth.uid() references auth.users(id),
  autor        text,
  calificacion smallint not null check (calificacion between 1 and 5),
  comentario   text not null check (char_length(trim(comentario)) between 1 and 500),
  creado_en    timestamptz default now()
);

create index if not exists idx_feedback_negocio
  on public.feedback (negocio_id, creado_en desc);

alter table public.feedback enable row level security;

-- Leer: solo el feedback de mi negocio.
drop policy if exists "feedback de mi negocio" on public.feedback;
create policy "feedback de mi negocio" on public.feedback
  for select to authenticated
  using (negocio_id = public.mi_negocio_id());

-- Crear: solo en mi negocio y a mi nombre (negocio_id/user_id salen por default).
drop policy if exists "crear feedback en mi negocio" on public.feedback;
create policy "crear feedback en mi negocio" on public.feedback
  for insert to authenticated
  with check (negocio_id = public.mi_negocio_id() and user_id = auth.uid());

-- Borrar: solo mi propio feedback.
drop policy if exists "borrar mi feedback" on public.feedback;
create policy "borrar mi feedback" on public.feedback
  for delete to authenticated
  using (user_id = auth.uid());